apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp-openbao
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: openchoreo
  sources:
    - repoURL: https://github.com/koorikla/openchoreo.git
      targetRevision: feat/multicluster-argocd
      ref: values
    - repoURL: ghcr.io/openbao/charts
      chart: openbao
      targetRevision: 0.29.3
      helm:
        valueFiles:
          - $values/values/common/openbao.yaml
  destination:
    name: in-cluster
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
