apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp-opensearch-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: openchoreo
  source:
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator/
    chart: opensearch-operator
    targetRevision: 3.0.2
  destination:
    name: in-cluster
    namespace: openchoreo-observability-plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
