apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: openchoreo
nodes:
- role: control-plane
  image: kindest/node:v1.31.2
  extraPortMappings:
  # Control Plane uses port range 8xxx
  # HTTP traffic to OpenChoreo UI and API (Kgateway LoadBalancer)
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "0.0.0.0"
  # HTTPS traffic to OpenChoreo UI and API (Kgateway LoadBalancer)
  - containerPort: 8443
    hostPort: 8443
    listenAddress: "0.0.0.0"
  # Data Plane uses port range 19xxx
  # HTTP traffic to workloads via Gateway
  - containerPort: 19080
    hostPort: 19080
    listenAddress: "0.0.0.0"
  # HTTPS traffic to workloads via Gateway
  - containerPort: 19443
    hostPort: 19443
    listenAddress: "0.0.0.0"
  # Workflow Plane uses port range 10xxx
  # Argo Workflows UI for development testing
  - containerPort: 10081
    hostPort: 10081
    listenAddress: "0.0.0.0"
  # Container Registry for storing built images
  - containerPort: 10082
    hostPort: 10082
    listenAddress: "0.0.0.0"
  # Observability Plane uses port range 11xxx
  # HTTP traffic to CLI and API (Kgateway LoadBalancer)
  - containerPort: 11080
    hostPort: 11080
    listenAddress: "0.0.0.0"
  # HTTPS traffic for OpenSearch access (Kgateway LoadBalancer)
  - containerPort: 11085
    hostPort: 11085
    listenAddress: "0.0.0.0"
  # OpenSearch Dashboard
  - containerPort: 5601
    hostPort: 11081
    listenAddress: "0.0.0.0"
  # OpenSearch API for Fluent Bit data pushing
  - containerPort: 9200
    hostPort: 11082
    listenAddress: "0.0.0.0"
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  apiServer:
    certSANs:
    - "localhost"
    - "127.0.0.1"
    - "host.k3d.internal"
    - "host.kind.internal"
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.k3d.internal:10082"]
    endpoint = ["http://host.k3d.internal:10082"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.kind.internal:10082"]
    endpoint = ["http://host.kind.internal:10082"]
