apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-prod-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: openchoreo
  source:
    repoURL: quay.io/jetstack/charts
    chart: cert-manager
    targetRevision: v1.21.1
    helm:
      values: |
        crds:
          enabled: true
  destination:
    name: dp-prod
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
