apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-prod-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: openchoreo
  source:
    repoURL: ghcr.io/external-secrets/charts
    chart: external-secrets
    targetRevision: 2.9.0
  destination:
    name: dp-prod
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
