apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-prod-kgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: openchoreo
  source:
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    chart: kgateway
    targetRevision: 2.4.3
  destination:
    name: dp-prod
    namespace: openchoreo-data-plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
