apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-prod-data-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: openchoreo
  sources:
    - repoURL: https://github.com/koorikla/openchoreo.git
      targetRevision: feat/multicluster-argocd
      ref: values
    - repoURL: ghcr.io/openchoreo/helm-charts
      chart: openchoreo-data-plane
      targetRevision: 1.2.3
      helm:
        valueFiles:
          - $values/values/dp-prod/data-plane.yaml
  destination:
    name: dp-prod
    namespace: openchoreo-data-plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 20
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
