apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oc-demo-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/koorikla/openchoreo.git
    targetRevision: main
    path: namespaces/default/projects
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
