apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openchoreo-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/koorikla/openchoreo.git
    targetRevision: main
    path: namespaces
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
